from __future__ import annotations

import asyncio
import json
import time
import uuid
from contextlib import AsyncExitStack
from dataclasses import dataclass
from typing import Any, Protocol
from urllib.parse import urlparse

import httpx
from scrapling.engines.toolbelt.custom import Response
from scrapling.fetchers import FetcherSession
from scrapling.parser import Selector

from .config import Settings
from .logging_setup import report_progress
from .models import JsonValue, RawDocument, SourceId, Status

SOLVER_TIMEOUT_SECONDS = 45


@dataclass
class Page:
    url: str
    status: int
    body: bytes
    transport: str = "scrapling"

    @property
    def text(self) -> str:
        return self.body.decode("utf-8", errors="replace")

    def selector(self) -> Selector:
        return Selector(self.text, url=self.url, adaptive=False)

    def json(self) -> JsonValue:
        try:
            return json.loads(self.body)
        except (ValueError, UnicodeDecodeError) as exc:
            raise FetchError(Status.PARSE_ERROR, "invalid JSON response", self) from exc

    def snapshot(self) -> RawDocument:
        return RawDocument(url=self.url, status=self.status, transport=self.transport, content=self.text)


class FetchError(Exception):
    def __init__(self, status: Status, message: str, page: Page | None = None) -> None:
        super().__init__(message)
        self.status = status
        self.page = page


class Session(Protocol):
    async def get(self, url: str, **kwargs: Any) -> Response: ...
    async def post(self, url: str, **kwargs: Any) -> Response: ...


class Client(Protocol):
    async def get(
        self,
        source: SourceId,
        url: str,
        *,
        headers: dict[str, str] | None = None,
        cookies: dict[str, str] | None = None,
        rendered: bool = False,
    ) -> Page: ...
    async def post_json(
        self, source: SourceId, url: str, payload: JsonValue, *, headers: dict[str, str] | None = None
    ) -> Page: ...


def response_issue(page: Page) -> tuple[Status, str] | None:
    text = page.text.lower()
    path = urlparse(page.url).path.lower()
    if "error 1005" in text or ("access denied" in text and "autonomous system" in text):
        return Status.IP_BLOCKED, "source denied the exit IP/ASN"
    if "not-available-in-your-region" in path or "not available in your region" in text:
        return Status.REGION_BLOCKED, "source is unavailable from this exit region"
    if "/login" in path or "log in  fc2" in text[:1000] or "此內容需要登入" in text:
        return Status.LOGIN_REQUIRED, "source requires an authenticated session"
    if "generated by cloudfront" in text and "request blocked" in text:
        return Status.BLOCKED, "CloudFront rejected the request"
    if "/doc/driver-verify" in path:
        return Status.BLOCKED, "JavBus verification gate"
    if page.status == 404:
        return Status.NOT_FOUND, "source returned HTTP 404"
    if page.status >= 400:
        return Status.BLOCKED if page.status in (401, 403) else Status.NETWORK_ERROR, f"HTTP {page.status}"
    return None


def is_cloudflare(page: Page) -> bool:
    text = page.text.lower()
    # Successful pages also embed Cloudflare's challenge-platform JS. A script URL
    # alone is not evidence that the requested document is a challenge page.
    title = page.selector().css("title::text").get("").strip().lower() if "<" in text[:200] else ""
    return (
        title.startswith(("just a moment", "attention required"))
        or ("cloudflare" in text and ("autonomous system" in text or "access denied" in title))
        or ("cf-chl-" in text and ("enable javascript and cookies" in text or "verify you are human" in text))
    )


class WebClient:
    """Pooled Scrapling sessions; solver cookies never migrate between exits."""

    def __init__(self, settings: Settings) -> None:
        self.settings = settings
        self._stack = AsyncExitStack()
        self._sessions: dict[tuple[SourceId, str], Session] = {}
        self._session_lock = asyncio.Lock()
        self._host_locks: dict[str, asyncio.Lock] = {}
        self._last_request: dict[str, float] = {}
        self._limit = asyncio.Semaphore(1)
        self._solver_limit = asyncio.Semaphore(1)
        self._solver_sessions: dict[tuple[SourceId, str], str] = {}
        self._solver_lock = asyncio.Lock()
        self._control: httpx.AsyncClient | None = None

    async def __aenter__(self) -> WebClient:
        await self._stack.__aenter__()
        self._control = await self._stack.enter_async_context(
            httpx.AsyncClient(
                timeout=SOLVER_TIMEOUT_SECONDS + 15,
                trust_env=False,
            )
        )
        return self

    async def __aexit__(self, *exc: Any) -> None:
        try:
            if self._control and self.settings.flaresolverr_url:
                for session in self._solver_sessions.values():
                    try:
                        await self._control.post(
                            self.settings.flaresolverr_url,
                            json={"cmd": "sessions.destroy", "session": session},
                            timeout=10,
                        )
                    except httpx.HTTPError:
                        pass
        finally:
            await self._stack.__aexit__(*exc)
            self._sessions.clear()
            self._solver_sessions.clear()

    async def _session(self, source: SourceId, url: str) -> Session:
        key = source, urlparse(url).netloc
        async with self._session_lock:
            if key not in self._sessions:
                self._sessions[key] = await self._stack.enter_async_context(
                    FetcherSession(
                        impersonate="chrome",
                        timeout=self.settings.timeout_seconds,
                        retries=0,
                        selector_config={"adaptive": False},
                    )
                )
            return self._sessions[key]

    async def _throttle(self, source: SourceId, host: str) -> None:
        interval = self.settings.source_interval(source)
        delay = interval - (time.monotonic() - self._last_request.get(host, 0))
        if delay > 0:
            await asyncio.sleep(delay)
        self._last_request[host] = time.monotonic()

    async def get(
        self,
        source: SourceId,
        url: str,
        *,
        headers: dict[str, str] | None = None,
        cookies: dict[str, str] | None = None,
        rendered: bool = False,
    ) -> Page:
        return await self._request(source, url, "GET", headers=headers, cookies=cookies, rendered=rendered)

    async def post_json(
        self, source: SourceId, url: str, payload: JsonValue, *, headers: dict[str, str] | None = None
    ) -> Page:
        return await self._request(source, url, "POST", payload=payload, headers=headers)

    async def image_bytes(self, source: SourceId, url: str, referer: str) -> bytes:
        page = await self._request(source, url, "GET", headers={"Referer": referer}, binary=True)
        return page.body

    async def _request(
        self,
        source: SourceId,
        url: str,
        method: str,
        *,
        payload: JsonValue = None,
        headers: dict[str, str] | None = None,
        cookies: dict[str, str] | None = None,
        rendered: bool = False,
        binary: bool = False,
    ) -> Page:
        parsed = urlparse(url)
        if parsed.scheme != "https" or not parsed.hostname:
            raise FetchError(Status.UNSUPPORTED, "site URLs must use HTTPS")
        host_lock = self._host_locks.setdefault(parsed.netloc, asyncio.Lock())
        config = self.settings.sites.get(source)
        # Artwork CDNs must not receive the source site's account cookies.
        cookie_host = urlparse(
            config.base_url
            if config and config.base_url
            else {
                SourceId.JAVDB: "https://javdb.com",
                SourceId.JAVBUS: "https://www.javbus.com",
                SourceId.DMM: "https://video.dmm.co.jp",
                SourceId.FC2: "https://adult.contents.fc2.com",
                SourceId.AVSOX: "https://avsox.click",
            }[source]
        ).hostname
        configured = config.cookie_values() if config and parsed.hostname == cookie_host else {}
        combined_cookies = {} if binary else {**(cookies or {}), **configured}
        async with host_lock, self._limit:
            if (
                method == "GET"
                and not binary
                and (rendered or (source, parsed.netloc) in self._solver_sessions)
            ):
                await self._throttle(source, parsed.netloc)
                return await self._render(source, url, combined_cookies)
            session = await self._session(source, url)
            for attempt in range(self.settings.retries + 1):
                await self._throttle(source, parsed.netloc)
                try:
                    kwargs = {"headers": headers or {}, "cookies": combined_cookies}
                    response = (
                        await session.get(url, **kwargs)
                        if method == "GET"
                        else await session.post(url, json=payload, **kwargs)
                    )
                    page = Page(str(response.url), response.status, response.body)
                except Exception as exc:  # Scrapling wraps several curl transport exception types.
                    if attempt < self.settings.retries:
                        await asyncio.sleep(self.settings.retry_delay_seconds)
                        continue
                    raise FetchError(
                        Status.NETWORK_ERROR, f"transport failed ({type(exc).__name__})"
                    ) from exc
                if is_cloudflare(page):
                    if binary:
                        raise FetchError(
                            Status.BLOCKED,
                            "image CDN challenged the request; solver API cannot return binary artwork",
                            page,
                        )
                    if method == "GET":
                        return await self._render(source, url, combined_cookies)
                    raise FetchError(
                        Status.BLOCKED,
                        "CF blocked a JSON endpoint; browser form POST cannot replace JSON",
                        page,
                    )
                if page.status == 429 or page.status >= 500:
                    if attempt < self.settings.retries:
                        retry_after = response.headers.get("retry-after", "")
                        seconds = (
                            min(int(retry_after), 30)
                            if retry_after.isdigit()
                            else self.settings.retry_delay_seconds
                        )
                        delay = 1 if seconds <= 1 else ((seconds + 4) // 5) * 5
                        await asyncio.sleep(delay)
                        continue
                if issue := response_issue(page):
                    raise FetchError(*issue, page)
                return page
        raise AssertionError("unreachable")

    async def _solver_call(self, data: dict[str, JsonValue]) -> dict[str, JsonValue]:
        if not self._control or not self.settings.flaresolverr_url:
            raise FetchError(Status.BLOCKED, "FlareSolverr is disabled or client is not open")
        try:
            response = await self._control.post(self.settings.flaresolverr_url, json=data)
            payload = response.json()
        except (httpx.HTTPError, ValueError) as exc:
            raise FetchError(
                Status.NETWORK_ERROR, f"FlareSolverr unavailable ({type(exc).__name__})"
            ) from exc
        if not isinstance(payload, dict):
            raise FetchError(Status.PARSE_ERROR, "invalid FlareSolverr response")
        if payload.get("status") != "ok":
            message = str(payload.get("message", "FlareSolverr failed"))
            status = Status.IP_BLOCKED if "banned" in message.lower() else Status.BLOCKED
            raise FetchError(status, message)
        return payload

    async def _render(self, source: SourceId, url: str, cookies: dict[str, str]) -> Page:
        report_progress("challenge", source=source)
        key = (source, urlparse(url).netloc)
        async with self._solver_limit:
            async with self._solver_lock:
                if key not in self._solver_sessions:
                    session = "eros-" + uuid.uuid4().hex
                    command: dict[str, JsonValue] = {"cmd": "sessions.create", "session": session}
                    await self._solver_call(command)
                    self._solver_sessions[key] = session
            payload = await self._solver_call(
                {
                    "cmd": "request.get",
                    "url": url,
                    "session": self._solver_sessions[key],
                    "maxTimeout": SOLVER_TIMEOUT_SECONDS * 1000,
                    # Browser-copied CF cookies belong to its original exit/UA.
                    # Forward login cookies while keeping the solver's own CF state.
                    "cookies": [
                        {"name": name, "value": value}
                        for name, value in cookies.items()
                        if name not in ("cf_clearance", "__cf_bm")
                    ],
                }
            )
            solution = payload.get("solution")
            if not isinstance(solution, dict) or not isinstance(solution.get("response"), str):
                raise FetchError(Status.PARSE_ERROR, "FlareSolverr returned no document")
            page = Page(
                str(solution.get("url", url)),
                int(solution.get("status", 200)),
                solution["response"].encode(),
                "flaresolverr",
            )
            if is_cloudflare(page):
                raise FetchError(Status.BLOCKED, "CF challenge remains after solver", page)
            if issue := response_issue(page):
                raise FetchError(*issue, page)
            return page
